### PR TITLE
Version 3.6

### LINKED ISSUE #402: Array support
#### Description
Support **numpy array** or **nested list**
#### Steps/Code to Reproduce
```pycon
>>> from pycm import ConfusionMatrix
>>> matrix = [[1,2,3],[4,6,1],[1,2,3]]
>>> cm = ConfusionMatrix(matrix = matrix)
>>> cm2 = ConfusionMatrix(matrix = matrix, classes=["L1","L2","L3"])
```
#### Expected Behavior
```
>>> cm.print_matrix()
Predict 0       1       2       
Actual
0       1       2       3       

1       4       6       1       

2       1       2       3       

>>> cm2.print_matrix()
Predict  L1       L2       L3       
Actual
L1       1        2        3        

L2       4        6        1        

L3       1        2        3 
```

#### Operating System
Windows 10
#### Python Version
Python 3.5.2
#### PyCM Version (Use : `pycm.__version__`)
3.3

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### Reference Issues/PRs
#349 
#350
close #402 
#### What does this implement/fix? Explain your changes.
Version 3.6

#### Acknowledgement
This version has been funded by the [NLnet foundation](https://nlnet.nl/project/PyCM/).

### CODE REVIEW

**Comment by sepandhaghighi** [comment]
@alirezazolanvari @sadrasabouri Hi folks
Please complete this review until **Wednesday - 2022-08-17 - 11:59 AM GMT+3:30**
**Notice:** Only review, don't need to merge

**Review by sadrasabouri — APPROVED** [review]
Ready to go :rocket:.

**Review by alirezazolanvari — APPROVED** [review]
LGTM!

**Review by sadrasabouri — APPROVED** [review]
LGTM :+1:

**Pull request merged**
