### PR TITLE
QI

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### Reference Issues/PRs
#267 
#### What does this implement/fix? Explain your changes.
- Yule's Q interpretation
- Minor edits in interpret functions

### CODE REVIEW

**Comment by sepandhaghighi** [comment]
@sadrasabouri @alirezazolanvari

Hi folks ;-)

This PR is for `Yule's Q interpretation`, please check carefully and give me some feedback ;-)
@alirezazolanvari please reformat added reference (`67`) in `README.md` - `QI` branch and then inform me

Notice 1 : Do not hurry, we have enough time ;-)
Notice 2 : This PR has 2 reviewer, so please don't merge this PR to dev branch before finishing the discussion

Best Regards
Sepand Haghighi

**Comment by sepandhaghighi** [comment]
@alirezazolanvari
Just another friendly reminder! ⏲

**Comment by alirezazolanvari** [comment]
@sepandhaghighi Shouldn't we update the compare section in the document?

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi Shouldn't we update the compare section in the document?

@alirezazolanvari 
Yeah you are right, I will update this section ASAP ;-)

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi Shouldn't we update the compare section in the document?

@alirezazolanvari 
Done!
If everything is OK, please merge this PR after approval ;-)

**Pull request merged**
