### PR TITLE
Improve HTML Report

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### What does this implement/fix? Explain your changes.
- `name` parameter removed from `html_init` function
- HTML report modified

### CODE REVIEW

**Comment by sepandhaghighi** [comment]
@sadrasabouri @alirezazolanvari 
Please review this PR

**Comment by sepandhaghighi** [comment]
@sadrasabouri @alirezazolanvari 
Please review this PR

**Review by sadrasabouri — APPROVED** [review]
LGTM

**Review by alirezazolanvari — APPROVED** [review]

**Comment by sepandhaghighi** [comment]
@alirezazolanvari 
If everything is okay, please merge this PR

**Pull request merged**
