### PR TITLE
Reference Section Removed from README.md

### PR DESCRIPTION
**Pull request by sadrasabouri**
#### What does this implement/fix? Explain your changes.
Our readme had been too long due to some unnecessary parts (like the reference section which is there at our documentations, too). This PR solve this problem by removing the reference section from the Readme.

### CODE REVIEW

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@sadrasabouri Thanks for your efforts 💯 
It seems we should update Contributing guidelines too.
- Removing `README.md` from `Overall statistic` section - 4th item
- Removing `README.md` from `Class statistic` section - 6th item

**Review by alirezazolanvari — CHANGES_REQUESTED** [review]
@sadrasabouri Thanks a lot for your efforts and sorry for my delay. I just have a minor comment. This PR is not related to NLnet. I think it's better to delete the nlnet label for this PR.

**Review by alirezazolanvari — APPROVED** [review]
Ready to merge!

**Review by sepandhaghighi — APPROVED** [review]
LGTM 🚀

**Pull request merged**
