### PR TITLE
Badges

### PR DESCRIPTION
**Pull request by sadrasabouri**
#### Reference Issues/PRs
#389 #397
#### What does this implement/fix? Explain your changes.
+ Google colab badge added.

<div align="center">
<a href="https://colab.research.google.com/github/sepandhaghighi/pycm/blob/master">
  Document
</a>
</div>

+ Discord badge added.

<div align="center">
<a href="https://discord.com/invite/zqpU2b3J3f">Discord Channel</a>

<a href="https://discord.com/invite/zqpU2b3J3f">Discord Channel</a>
</div>

### CODE REVIEW

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@sadrasabouri 

Also, add the badge to these pages:

1. `Try PyCM in your browser!` section in `README.md`
2. `Try PyCM in your browser!` section in `Document/README.md`

```
PyCM can be used online in interactive Jupyter Notebooks via the Binder or Colab services! Try it out now! :
```

**Comment by sadrasabouri** [comment]
@sepandhaghighi Please review it again.
And just a tiny point, in `Document.ipynb` since we don't have
```
pip install pycm
```
block, document won't be mannerd as a plug and play notebook.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi Please review it again. And just a tiny point, in `Document.ipynb` since we don't have
> 
> ```
> pip install pycm
> ```
> 
> block, document won't be mannerd as a plug and play notebook.

Ow, it's an issue.
Let talk about it in the next weekly session.

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@sadrasabouri Please consider the following:

1. Remove `Support` link from TOC (Table of contents)
2. Use this structure for `Issues & bug reports` section
```
1. Fill an issue and describe it. We'll check it ASAP! 
    - Please complete the issue template
2. Discord Server : [https://discord.com/invite/zqpU2b3J3f](https://discord.com/invite/zqpU2b3J3f)
3. Website : [https://www.pycm.ir](https://www.pycm.ir)		
4. Mailing List : [https://mail.python.org/mailman3/lists/pycm.python.org/](https://mail.python.org/mailman3/lists/pycm.python.org/)
5. Email : [info@pycm.ir](mailto:info@pycm.ir "info@pycm.ir")
```

**Review by sepandhaghighi — APPROVED** [review]
LGTM

**Comment by sepandhaghighi** [comment]
@sadrasabouri @alirezazolanvari Please review this PR 💯

**Comment by sadrasabouri** [comment]
> @sadrasabouri @alirezazolanvari Please review this PR 💯

Seems OK to me.

**Pull request merged**
